############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 22/11/2024        #
############################
---
apiVersion: v1
appVersion: 7.15.0
description: Official Elastic helm chart for Filebeat
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/beats.png
maintainers:
- email: helm-charts@elastic.co
  name: Elastic
name: filebeat
sources:
- https://github.com/elastic/beats
version: 7.15.0