############################
# @author Elias De Hondt   #
# @see https://eliasdh.com #
# @since 22/11/2024        #
############################
---
{{- if .Values.kibanaConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kibana.fullname" . }}-config
  labels: {{ include "kibana.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.kibanaConfig }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}
{{- end -}}