{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kibana.fullname" . }}
  labels: {{ include "kibana.labels" . | nindent 4 }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hosts[0] }}
      secretName: {{ .Values.ingress.tls[0].secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts[0] }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "kibana.fullname" . }}
                port:
                  number: 5601
{{- end }}